import React, { useState } from 'react';
import axiosInstance from '../../shared/api/axiosInstance';
import { useAuth } from '../../shared/context/AuthContext';
import { FileText, Loader2, Play } from 'lucide-react';

const SummaryView = () => {
  const { showToast } = useAuth();
  const [repoInput, setRepoInput] = useState('');
  const [currentRepoId, setCurrentRepoId] = useState('');
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState(null);
  const [error, setError] = useState('');

  const fetchSummary = async (e) => {
    e.preventDefault();
    if (!repoInput) return;
    setLoading(true);
    setError('');
    
    try {
      let targetId = repoInput;
      const isObjectId = /^[0-9a-fA-F]{24}$/.test(repoInput);
      if (!isObjectId) {
        const lookupRes = await axiosInstance.get(`/repositories/lookup?url=${encodeURIComponent(repoInput)}`);
        targetId = lookupRes.data.data.repositoryId;
      }
      setCurrentRepoId(targetId);

      try {
        const res = await axiosInstance.get(`/summary/${targetId}`);
        setSummary(res.data.data);
      } catch (fetchErr) {
        if (fetchErr.response?.status === 404) {
          // No summary exists yet — auto-generate one
          const genRes = await axiosInstance.post(`/summary/${targetId}/generate`);
          setSummary(genRes.data.data);
          if (showToast) {
            showToast('Summary auto-generated successfully!', 'success');
          }
        } else {
          throw fetchErr;
        }
      }
    } catch (err) {
      setError('Failed to fetch or generate summary.');
    } finally {
      setLoading(false);
    }
  };

  const generateSummary = async () => {
    if (!currentRepoId) return;
    setLoading(true);
    setError('');
    
    try {
      const res = await axiosInstance.post(`/summary/${currentRepoId}/generate`);
      setSummary(res.data.data);
      if (showToast) {
        showToast('Summary generated successfully!', 'success');
      } else {
        alert('Summary generated successfully!');
      }
    } catch (err) {
      setError('Failed to start summary generation.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-[calc(100vh-2rem)] p-8 max-w-5xl mx-auto">
      <div className="mb-6">
        <h1 className="text-3xl font-bold text-white mb-2">Repository Summaries</h1>
        <p className="text-zinc-400">High-level documentation and summaries generated by AI.</p>
      </div>

      <div className="mb-8">
        <form onSubmit={fetchSummary} className="flex gap-4 max-w-md">
          <label htmlFor="repo-id-input" className="sr-only">Repository URL or ID</label>
          <input
            id="repo-id-input"
            type="text"
            placeholder="Repository URL or ID"
            value={repoInput}
            onChange={(e) => setRepoInput(e.target.value)}
            className="flex-1 bg-black/40 border border-white/10 rounded-xl px-4 py-2.5 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 text-zinc-200 backdrop-blur-sm"
          />
          <button
            type="submit"
            aria-label="Fetch Summary"
            disabled={loading || !repoInput}
            className="bg-indigo-600 hover:bg-indigo-500 text-white px-6 py-2.5 rounded-xl font-medium transition-colors flex items-center gap-2 disabled:opacity-50"
          >
            {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <FileText className="w-5 h-5" />}
            Fetch
          </button>
        </form>
      </div>

      {error && (
        <div role="alert" className="bg-red-500/10 border border-red-500/50 text-red-400 p-4 rounded-xl mb-6 flex justify-between items-center">
          <span>{error}</span>
          {error.includes('Generate') && (
            <button 
              onClick={generateSummary}
              aria-label="Generate Summary Now"
              className="px-4 py-2 bg-red-500/20 hover:bg-red-500/30 text-red-300 rounded-lg transition-colors flex items-center gap-2 text-sm font-medium"
            >
              <Play className="w-4 h-4" /> Generate Now
            </button>
          )}
        </div>
      )}

      <div aria-live="polite" className="flex-1 glass-panel rounded-2xl p-8 overflow-y-auto shadow-lg text-zinc-200">
        {summary ? (
          <div className="prose prose-invert max-w-none">
            <h2 className="text-2xl font-bold text-indigo-300 mb-4 border-b border-white/10 pb-2">Narrative Overview</h2>
            <p className="whitespace-pre-wrap leading-relaxed">{summary.aiNarrative || summary.narrative}</p>

            <h2 className="text-2xl font-bold text-cyan-300 mt-8 mb-4 border-b border-white/10 pb-2">Key Highlights</h2>
            <ul className="list-disc pl-5 space-y-2">
              {(summary.highlights || []).map((highlight, idx) => (
                <li key={idx} className="text-zinc-300">{highlight}</li>
              ))}
            </ul>

            <h2 className="text-2xl font-bold text-emerald-300 mt-8 mb-4 border-b border-white/10 pb-2">Architecture Changes</h2>
            <ul className="list-disc pl-5 space-y-2">
              {(summary.architectureChanges || []).map((change, idx) => (
                <li key={idx} className="text-zinc-300">{change}</li>
              ))}
            </ul>
          </div>
        ) : (
          <div className="h-full flex flex-col items-center justify-center text-center">
            <div className="w-16 h-16 bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 rounded-full flex items-center justify-center mb-6 shadow-[0_0_20px_rgba(99,102,241,0.2)]">
              <FileText className="w-8 h-8" />
            </div>
            <h2 className="text-xl font-bold text-white mb-2">No Summary Displayed</h2>
            <p className="text-zinc-400 max-w-md">
              Enter a repository ID to view its generated documentation, architectural overview, and key components.
            </p>
          </div>
        )}
      </div>
    </div>
  );
};

export default SummaryView;
