'use strict';

module.exports = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_INVALID_RESET_TOKEN: 'AUTH_INVALID_RESET_TOKEN',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',

  // Repository
  REPO_NOT_FOUND: 'REPO_NOT_FOUND',
  REPO_ALREADY_EXISTS: 'REPO_ALREADY_EXISTS',
  REPO_ACCESS_DENIED: 'REPO_ACCESS_DENIED',
  REPO_INVALID_URL: 'REPO_INVALID_URL',
  REPO_ANALYSIS_FAILED: 'REPO_ANALYSIS_FAILED',

  // GitHub
  GITHUB_API_ERROR: 'GITHUB_API_ERROR',
  GITHUB_RATE_LIMIT: 'GITHUB_RATE_LIMIT',
  GITHUB_WEBHOOK_INVALID: 'GITHUB_WEBHOOK_INVALID',
  GITHUB_NOT_CONNECTED: 'GITHUB_NOT_CONNECTED',

  // AI
  AI_PROVIDER_ERROR: 'AI_PROVIDER_ERROR',
  AI_EMBEDDING_FAILED: 'AI_EMBEDDING_FAILED',
  AI_NO_EMBEDDINGS: 'AI_NO_EMBEDDINGS',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // General
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
};
